version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
  - dependency-name: github.com/libp2p/go-libp2p-core
    versions:
    - 0.8.0
  - dependency-name: github.com/multiformats/go-multihash
    versions:
    - 0.0.14
