// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: drive.proto

package drive_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Contract struct {
	Drive                []byte   `protobuf:"bytes,1,opt,name=drive,proto3" json:"drive,omitempty"`
	Owner                []byte   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Replicators          [][]byte `protobuf:"bytes,3,rep,name=replicators,proto3" json:"replicators,omitempty"`
	Root                 []byte   `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	Duration             int64    `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	BillingPrice         int64    `protobuf:"varint,6,opt,name=billingPrice,proto3" json:"billingPrice,omitempty"`
	BillingPeriod        int64    `protobuf:"varint,7,opt,name=billingPeriod,proto3" json:"billingPeriod,omitempty"`
	Created              int64    `protobuf:"varint,8,opt,name=created,proto3" json:"created,omitempty"`
	Space                int64    `protobuf:"varint,9,opt,name=space,proto3" json:"space,omitempty"`
	PayedReplicas        uint32   `protobuf:"varint,10,opt,name=payedReplicas,proto3" json:"payedReplicas,omitempty"`
	MinReplicators       uint32   `protobuf:"varint,11,opt,name=minReplicators,proto3" json:"minReplicators,omitempty"`
	PercentApprovers     uint32   `protobuf:"varint,12,opt,name=percentApprovers,proto3" json:"percentApprovers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_acb65799e804e3dc, []int{0}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return m.Size()
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetDrive() []byte {
	if m != nil {
		return m.Drive
	}
	return nil
}

func (m *Contract) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Contract) GetReplicators() [][]byte {
	if m != nil {
		return m.Replicators
	}
	return nil
}

func (m *Contract) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Contract) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Contract) GetBillingPrice() int64 {
	if m != nil {
		return m.BillingPrice
	}
	return 0
}

func (m *Contract) GetBillingPeriod() int64 {
	if m != nil {
		return m.BillingPeriod
	}
	return 0
}

func (m *Contract) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Contract) GetSpace() int64 {
	if m != nil {
		return m.Space
	}
	return 0
}

func (m *Contract) GetPayedReplicas() uint32 {
	if m != nil {
		return m.PayedReplicas
	}
	return 0
}

func (m *Contract) GetMinReplicators() uint32 {
	if m != nil {
		return m.MinReplicators
	}
	return 0
}

func (m *Contract) GetPercentApprovers() uint32 {
	if m != nil {
		return m.PercentApprovers
	}
	return 0
}

type Invite struct {
	Drive                []byte   `protobuf:"bytes,1,opt,name=drive,proto3" json:"drive,omitempty"`
	Owner                []byte   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	BillingPrice         int64    `protobuf:"varint,4,opt,name=billingPrice,proto3" json:"billingPrice,omitempty"`
	BillingPeriod        int64    `protobuf:"varint,5,opt,name=billingPeriod,proto3" json:"billingPeriod,omitempty"`
	Space                int64    `protobuf:"varint,6,opt,name=space,proto3" json:"space,omitempty"`
	PayedReplicas        uint32   `protobuf:"varint,7,opt,name=payedReplicas,proto3" json:"payedReplicas,omitempty"`
	MinReplicators       uint32   `protobuf:"varint,8,opt,name=minReplicators,proto3" json:"minReplicators,omitempty"`
	PercentApprovers     uint32   `protobuf:"varint,9,opt,name=percentApprovers,proto3" json:"percentApprovers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invite) Reset()         { *m = Invite{} }
func (m *Invite) String() string { return proto.CompactTextString(m) }
func (*Invite) ProtoMessage()    {}
func (*Invite) Descriptor() ([]byte, []int) {
	return fileDescriptor_acb65799e804e3dc, []int{1}
}
func (m *Invite) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Invite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Invite.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Invite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invite.Merge(m, src)
}
func (m *Invite) XXX_Size() int {
	return m.Size()
}
func (m *Invite) XXX_DiscardUnknown() {
	xxx_messageInfo_Invite.DiscardUnknown(m)
}

var xxx_messageInfo_Invite proto.InternalMessageInfo

func (m *Invite) GetDrive() []byte {
	if m != nil {
		return m.Drive
	}
	return nil
}

func (m *Invite) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Invite) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Invite) GetBillingPrice() int64 {
	if m != nil {
		return m.BillingPrice
	}
	return 0
}

func (m *Invite) GetBillingPeriod() int64 {
	if m != nil {
		return m.BillingPeriod
	}
	return 0
}

func (m *Invite) GetSpace() int64 {
	if m != nil {
		return m.Space
	}
	return 0
}

func (m *Invite) GetPayedReplicas() uint32 {
	if m != nil {
		return m.PayedReplicas
	}
	return 0
}

func (m *Invite) GetMinReplicators() uint32 {
	if m != nil {
		return m.MinReplicators
	}
	return 0
}

func (m *Invite) GetPercentApprovers() uint32 {
	if m != nil {
		return m.PercentApprovers
	}
	return 0
}

type SContract struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Drive                []byte   `protobuf:"bytes,2,opt,name=drive,proto3" json:"drive,omitempty"`
	File                 []byte   `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Vmversion            uint64   `protobuf:"varint,4,opt,name=vmversion,proto3" json:"vmversion,omitempty"`
	Status               uint32   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Functions            []string `protobuf:"bytes,6,rep,name=functions,proto3" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SContract) Reset()         { *m = SContract{} }
func (m *SContract) String() string { return proto.CompactTextString(m) }
func (*SContract) ProtoMessage()    {}
func (*SContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_acb65799e804e3dc, []int{2}
}
func (m *SContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SContract.Merge(m, src)
}
func (m *SContract) XXX_Size() int {
	return m.Size()
}
func (m *SContract) XXX_DiscardUnknown() {
	xxx_messageInfo_SContract.DiscardUnknown(m)
}

var xxx_messageInfo_SContract proto.InternalMessageInfo

func (m *SContract) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SContract) GetDrive() []byte {
	if m != nil {
		return m.Drive
	}
	return nil
}

func (m *SContract) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *SContract) GetVmversion() uint64 {
	if m != nil {
		return m.Vmversion
	}
	return 0
}

func (m *SContract) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SContract) GetFunctions() []string {
	if m != nil {
		return m.Functions
	}
	return nil
}

func init() {
	proto.RegisterType((*Contract)(nil), "drive_pb.Contract")
	proto.RegisterType((*Invite)(nil), "drive_pb.Invite")
	proto.RegisterType((*SContract)(nil), "drive_pb.SContract")
}

func init() { proto.RegisterFile("drive.proto", fileDescriptor_acb65799e804e3dc) }

var fileDescriptor_acb65799e804e3dc = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0xc7, 0x27, 0xdb, 0x71, 0xec, 0x13, 0x27, 0x04, 0x31, 0x86, 0x18, 0xc3, 0x98, 0x30, 0x86,
	0xd9, 0xc5, 0x6e, 0xf6, 0x04, 0xdb, 0xae, 0x76, 0x37, 0xb4, 0x07, 0x28, 0x8e, 0xad, 0x14, 0x81,
	0x23, 0x09, 0x59, 0x71, 0xe9, 0x9b, 0xb4, 0xaf, 0xd0, 0x27, 0xe9, 0x65, 0x1f, 0xa1, 0xa4, 0xaf,
	0xd1, 0x8b, 0x22, 0x39, 0x1f, 0x4e, 0x3f, 0xd3, 0x3b, 0xfd, 0x7f, 0xe7, 0xe8, 0xe0, 0xf3, 0xc3,
	0x82, 0x51, 0xa5, 0x79, 0xcb, 0x7e, 0x28, 0x2d, 0x8d, 0xc4, 0x91, 0x0b, 0x27, 0x6a, 0x3e, 0xbb,
	0xf7, 0x20, 0xfa, 0x23, 0x85, 0xd1, 0x45, 0x69, 0xf0, 0x47, 0x18, 0xb8, 0x02, 0x41, 0x19, 0xca,
	0x13, 0xda, 0x05, 0x4b, 0xe5, 0x99, 0x60, 0x9a, 0x78, 0x1d, 0x75, 0x01, 0x67, 0x30, 0xd2, 0x4c,
	0xd5, 0xbc, 0x2c, 0x8c, 0xd4, 0x0d, 0xf1, 0x33, 0x3f, 0x4f, 0x68, 0x1f, 0x61, 0x0c, 0x81, 0x96,
	0xd2, 0x90, 0xc0, 0x5d, 0x73, 0x67, 0xfc, 0x19, 0xa2, 0x6a, 0xa5, 0x0b, 0xc3, 0xa5, 0x20, 0x83,
	0x0c, 0xe5, 0x3e, 0xdd, 0x65, 0x3c, 0x83, 0x64, 0xce, 0xeb, 0x9a, 0x8b, 0xd3, 0x7f, 0x9a, 0x97,
	0x8c, 0x84, 0xae, 0x7e, 0xc0, 0xf0, 0x57, 0x18, 0x6f, 0x33, 0xd3, 0x5c, 0x56, 0x64, 0xe8, 0x9a,
	0x0e, 0x21, 0x26, 0x30, 0x2c, 0x35, 0x2b, 0x0c, 0xab, 0x48, 0xe4, 0xea, 0xdb, 0x68, 0x77, 0x69,
	0x54, 0x51, 0x32, 0x12, 0x3b, 0xde, 0x05, 0x3b, 0x55, 0x15, 0xe7, 0xac, 0xa2, 0xdd, 0xd7, 0x37,
	0x04, 0x32, 0x94, 0x8f, 0xe9, 0x21, 0xc4, 0xdf, 0x60, 0xb2, 0xe4, 0x82, 0xf6, 0x96, 0x1e, 0xb9,
	0xb6, 0x47, 0x14, 0x7f, 0x87, 0xa9, 0x62, 0xba, 0x64, 0xc2, 0xfc, 0x52, 0x4a, 0xcb, 0x96, 0xe9,
	0x86, 0x24, 0xae, 0xf3, 0x09, 0x9f, 0x5d, 0x79, 0x10, 0xfe, 0x15, 0x2d, 0x37, 0xec, 0x5d, 0xf2,
	0xfb, 0x1a, 0xfd, 0x37, 0x34, 0x06, 0xc7, 0x68, 0x1c, 0x3c, 0xa7, 0x71, 0x27, 0x2b, 0x7c, 0x55,
	0xd6, 0xf0, 0x38, 0x59, 0xd1, 0xd1, 0xb2, 0xe2, 0x17, 0x64, 0x5d, 0x22, 0x88, 0xff, 0xef, 0x7e,
	0xd6, 0x09, 0x78, 0xbc, 0xda, 0xc8, 0xf2, 0x78, 0xb5, 0xf7, 0xe7, 0xf5, 0xfd, 0x61, 0x08, 0x16,
	0xbc, 0x66, 0xce, 0x52, 0x42, 0xdd, 0x19, 0x7f, 0x81, 0xb8, 0x5d, 0xda, 0x89, 0x56, 0x9f, 0xd5,
	0x13, 0xd0, 0x3d, 0xc0, 0x9f, 0x20, 0x6c, 0x4c, 0x61, 0x56, 0x8d, 0x93, 0x32, 0xa6, 0x9b, 0x64,
	0x6f, 0x2d, 0x56, 0xa2, 0xb4, 0x8e, 0x1b, 0x12, 0x66, 0x7e, 0x1e, 0xd3, 0x3d, 0xf8, 0x3d, 0xbd,
	0x5e, 0xa7, 0xe8, 0x66, 0x9d, 0xa2, 0xdb, 0x75, 0x8a, 0x2e, 0xee, 0xd2, 0x0f, 0xf3, 0xd0, 0x3d,
	0xb5, 0x9f, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x50, 0xe2, 0xb7, 0x87, 0x79, 0x03, 0x00, 0x00,
}

func (m *Contract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.PercentApprovers != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.PercentApprovers))
		i--
		dAtA[i] = 0x60
	}
	if m.MinReplicators != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.MinReplicators))
		i--
		dAtA[i] = 0x58
	}
	if m.PayedReplicas != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.PayedReplicas))
		i--
		dAtA[i] = 0x50
	}
	if m.Space != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.Space))
		i--
		dAtA[i] = 0x48
	}
	if m.Created != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.Created))
		i--
		dAtA[i] = 0x40
	}
	if m.BillingPeriod != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.BillingPeriod))
		i--
		dAtA[i] = 0x38
	}
	if m.BillingPrice != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.BillingPrice))
		i--
		dAtA[i] = 0x30
	}
	if m.Duration != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Replicators) > 0 {
		for iNdEx := len(m.Replicators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Replicators[iNdEx])
			copy(dAtA[i:], m.Replicators[iNdEx])
			i = encodeVarintDrive(dAtA, i, uint64(len(m.Replicators[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Drive) > 0 {
		i -= len(m.Drive)
		copy(dAtA[i:], m.Drive)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.Drive)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Invite) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Invite) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Invite) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.PercentApprovers != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.PercentApprovers))
		i--
		dAtA[i] = 0x48
	}
	if m.MinReplicators != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.MinReplicators))
		i--
		dAtA[i] = 0x40
	}
	if m.PayedReplicas != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.PayedReplicas))
		i--
		dAtA[i] = 0x38
	}
	if m.Space != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.Space))
		i--
		dAtA[i] = 0x30
	}
	if m.BillingPeriod != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.BillingPeriod))
		i--
		dAtA[i] = 0x28
	}
	if m.BillingPrice != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.BillingPrice))
		i--
		dAtA[i] = 0x20
	}
	if m.Duration != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Drive) > 0 {
		i -= len(m.Drive)
		copy(dAtA[i:], m.Drive)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.Drive)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Functions) > 0 {
		for iNdEx := len(m.Functions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Functions[iNdEx])
			copy(dAtA[i:], m.Functions[iNdEx])
			i = encodeVarintDrive(dAtA, i, uint64(len(m.Functions[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Status != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.Vmversion != 0 {
		i = encodeVarintDrive(dAtA, i, uint64(m.Vmversion))
		i--
		dAtA[i] = 0x20
	}
	if len(m.File) > 0 {
		i -= len(m.File)
		copy(dAtA[i:], m.File)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.File)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Drive) > 0 {
		i -= len(m.Drive)
		copy(dAtA[i:], m.Drive)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.Drive)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDrive(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDrive(dAtA []byte, offset int, v uint64) int {
	offset -= sovDrive(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Drive)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	if len(m.Replicators) > 0 {
		for _, b := range m.Replicators {
			l = len(b)
			n += 1 + l + sovDrive(uint64(l))
		}
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	if m.Duration != 0 {
		n += 1 + sovDrive(uint64(m.Duration))
	}
	if m.BillingPrice != 0 {
		n += 1 + sovDrive(uint64(m.BillingPrice))
	}
	if m.BillingPeriod != 0 {
		n += 1 + sovDrive(uint64(m.BillingPeriod))
	}
	if m.Created != 0 {
		n += 1 + sovDrive(uint64(m.Created))
	}
	if m.Space != 0 {
		n += 1 + sovDrive(uint64(m.Space))
	}
	if m.PayedReplicas != 0 {
		n += 1 + sovDrive(uint64(m.PayedReplicas))
	}
	if m.MinReplicators != 0 {
		n += 1 + sovDrive(uint64(m.MinReplicators))
	}
	if m.PercentApprovers != 0 {
		n += 1 + sovDrive(uint64(m.PercentApprovers))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Invite) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Drive)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	if m.Duration != 0 {
		n += 1 + sovDrive(uint64(m.Duration))
	}
	if m.BillingPrice != 0 {
		n += 1 + sovDrive(uint64(m.BillingPrice))
	}
	if m.BillingPeriod != 0 {
		n += 1 + sovDrive(uint64(m.BillingPeriod))
	}
	if m.Space != 0 {
		n += 1 + sovDrive(uint64(m.Space))
	}
	if m.PayedReplicas != 0 {
		n += 1 + sovDrive(uint64(m.PayedReplicas))
	}
	if m.MinReplicators != 0 {
		n += 1 + sovDrive(uint64(m.MinReplicators))
	}
	if m.PercentApprovers != 0 {
		n += 1 + sovDrive(uint64(m.PercentApprovers))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	l = len(m.Drive)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	l = len(m.File)
	if l > 0 {
		n += 1 + l + sovDrive(uint64(l))
	}
	if m.Vmversion != 0 {
		n += 1 + sovDrive(uint64(m.Vmversion))
	}
	if m.Status != 0 {
		n += 1 + sovDrive(uint64(m.Status))
	}
	if len(m.Functions) > 0 {
		for _, s := range m.Functions {
			l = len(s)
			n += 1 + l + sovDrive(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovDrive(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDrive(x uint64) (n int) {
	return sovDrive(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDrive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Drive", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Drive = append(m.Drive[:0], dAtA[iNdEx:postIndex]...)
			if m.Drive == nil {
				m.Drive = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicators", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Replicators = append(m.Replicators, make([]byte, postIndex-iNdEx))
			copy(m.Replicators[len(m.Replicators)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BillingPrice", wireType)
			}
			m.BillingPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BillingPrice |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BillingPeriod", wireType)
			}
			m.BillingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BillingPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			m.Created = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Created |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Space", wireType)
			}
			m.Space = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Space |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayedReplicas", wireType)
			}
			m.PayedReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayedReplicas |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReplicators", wireType)
			}
			m.MinReplicators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinReplicators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PercentApprovers", wireType)
			}
			m.PercentApprovers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PercentApprovers |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDrive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDrive
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDrive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Invite) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDrive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Invite: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Invite: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Drive", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Drive = append(m.Drive[:0], dAtA[iNdEx:postIndex]...)
			if m.Drive == nil {
				m.Drive = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BillingPrice", wireType)
			}
			m.BillingPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BillingPrice |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BillingPeriod", wireType)
			}
			m.BillingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BillingPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Space", wireType)
			}
			m.Space = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Space |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayedReplicas", wireType)
			}
			m.PayedReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayedReplicas |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReplicators", wireType)
			}
			m.MinReplicators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinReplicators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PercentApprovers", wireType)
			}
			m.PercentApprovers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PercentApprovers |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDrive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDrive
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDrive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDrive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Drive", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Drive = append(m.Drive[:0], dAtA[iNdEx:postIndex]...)
			if m.Drive == nil {
				m.Drive = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field File", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.File = append(m.File[:0], dAtA[iNdEx:postIndex]...)
			if m.File == nil {
				m.File = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vmversion", wireType)
			}
			m.Vmversion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vmversion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Functions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDrive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDrive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Functions = append(m.Functions, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDrive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDrive
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthDrive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDrive(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDrive
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDrive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDrive
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDrive
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDrive
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDrive        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDrive          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDrive = fmt.Errorf("proto: unexpected end of group")
)
